blank_issues_enabled: false

contact_links:
    - name: Discord
      url: https://discord.gg/ActsEuc2Bh
      about: Get support in my Discord server

    - name: Discussions
      url: https://github.com/RedGuy12/paul-reid-photography/discussions/new
      about: "Chat, ask for help, and share what you've made here"
