name: Lint Commit Messages
on: [pull_request, push]

jobs:
    commitlint:
        runs-on: ubuntu-20.0.4
        steps:
            - uses: actions/checkout@v3.0.2
              with:
                  fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v5.3.0
