name: Format and lint
on: [push, pull_request, workflow_dispatch]

jobs:
    run:
        name: Lint
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.5
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.TOKEN || github.token }}

            - name: Setup Node.JS
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 16
                  cache: "npm"

            - name: Install
              run: npm install --force

            - name: Mustaches
              run: npm run lint:mustaches

            - name: Prettier
              if: ${{ !cancelled() }}
              run: npm run lint:prettier

            - name: Typescript
              if: ${{ !cancelled() }}
              run: npm run lint:typescript

            - name: ESLint
              if: ${{ !cancelled() }}
              run: npm run lint:eslint

            - name: Revert
              if: ${{ !cancelled() }}
              run: git checkout HEAD -- package-lock.json package.json

            - name: Commit
              if: ${{ !cancelled() }}
              uses: stefanzweifel/git-auto-commit-action@v4.12.0
              with:
                  commit_message: "Lint and format code"
                  branch: ${{ github.head_ref }}
                  commit_options: "--signoff"
                  # commit_user_name: wgytbot
                  # commit_user_email: 83586655+wgytbot@users.noreply.github.com
                  # commit_author: wgytbot <83586655+wgytbot@users.noreply.github.com>
